/**
 *
 * Clase: GestionarPreciosTratamiento
 *
 * @version: 0.1
 *
 * @Fecha de creación: 13/06/2020
 *
 * Fecha de Modificación:
 *
 * @author migue 1102838994
 *
 * Copyrigth: CECAR
 *
 */
package edu.cecar.vistas;

import edu.cecar.componentes.TextPrompt;
import edu.cecar.componentes.baseDatos.ConectarMySQL;
import edu.cecar.controladores.ControladorPrecio;
import edu.cecar.modelo.Precio;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author migue
 */
public class GestionarPreciosTratamiento extends javax.swing.JInternalFrame {

    private static ControladorPrecio controladorPrecio;

    /**
     * Creates new form GestionarUsuarios
     */
    public GestionarPreciosTratamiento() {
        initComponents();
        // Se hace que campo de texto Identidicación este listo para ser editado        
        jTPrecio.grabFocus();

        alInicio();
        textoCampos();
        cargarImagenesBotones();

        // Realizamos la conexión con la base de datos
        try {
            ConectarMySQL.getConectarMySQL("127.0.0.1", "sif", "root", "");
        } catch (Exception e1) {
            // TODO Auto-generated catch block
            //e1.printStackTrace();
            JOptionPane.showMessageDialog(null,
                    "Error al conectar con la Base de datos");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTPrecio = new javax.swing.JTextField();
        jTCodigoAreaCuerpo = new javax.swing.JTextField();
        jTValor = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jBNuevo = new javax.swing.JButton();
        jBRegistar = new javax.swing.JButton();
        jBConsultar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setTitle("Gestionar Precio de Tratamientos");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Información Precio", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 0, 18))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jPanel1.setLayout(null);

        jTPrecio.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        jTPrecio.setBorder(null);
        jTPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTPrecioActionPerformed(evt);
            }
        });
        jPanel1.add(jTPrecio);
        jTPrecio.setBounds(80, 50, 150, 30);

        jTCodigoAreaCuerpo.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        jTCodigoAreaCuerpo.setBorder(null);
        jPanel1.add(jTCodigoAreaCuerpo);
        jTCodigoAreaCuerpo.setBounds(50, 100, 210, 30);

        jTValor.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        jTValor.setBorder(null);
        jPanel1.add(jTValor);
        jTValor.setBounds(50, 150, 210, 30);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(70, 80, 170, 10);
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(50, 130, 210, 10);
        jPanel1.add(jSeparator4);
        jSeparator4.setBounds(50, 180, 210, 10);

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("$");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 140, 20, 50);

        jPanel4.add(jPanel1);
        jPanel1.setBounds(10, 10, 310, 240);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Operaciones", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 0, 18))); // NOI18N
        jPanel2.setLayout(null);

        jBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoActionPerformed(evt);
            }
        });
        jPanel2.add(jBNuevo);
        jBNuevo.setBounds(10, 100, 150, 50);

        jBRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegistarActionPerformed(evt);
            }
        });
        jPanel2.add(jBRegistar);
        jBRegistar.setBounds(20, 160, 140, 50);

        jBConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultarActionPerformed(evt);
            }
        });
        jPanel2.add(jBConsultar);
        jBConsultar.setBounds(20, 40, 140, 50);

        jPanel4.add(jPanel2);
        jPanel2.setBounds(350, 20, 190, 230);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegistarActionPerformed

        // Se procede a realizar operaciones con los datos 
        if (jTPrecio.getText().equals("")
                || jTCodigoAreaCuerpo.getText().equals("")
                || jTValor.getText().equals("")) {

            JOptionPane.showMessageDialog(null,
                    "Verificar los datos ingresados");
        } else {

            Precio precio
                    = new Precio(Integer.parseInt(
                            jTPrecio.getText()),
                            Integer.parseInt(jTCodigoAreaCuerpo.getText()),
                            jTValor.getText());
            guardar(precio);
        }

    }//GEN-LAST:event_jBRegistarActionPerformed

    private void jBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoActionPerformed

        nuevoPrecio();
    }//GEN-LAST:event_jBNuevoActionPerformed

    private void jBConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultarActionPerformed

        consultarPrecio();
    }//GEN-LAST:event_jBConsultarActionPerformed

    private void jTPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTPrecioActionPerformed

        consultarPrecio();
    }//GEN-LAST:event_jTPrecioActionPerformed

    public static ControladorPrecio getControladorPrecio() {

        if (controladorPrecio == null) {
            controladorPrecio = new ControladorPrecio();
        }

        return controladorPrecio;

    }

    public void guardar(Precio precio) {

        try {

            getControladorPrecio().guardar(precio);
            JOptionPane.showMessageDialog(null,
                    "Precio Almacenado correctamente");
            nuevoPrecio();
            alInicio();

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null,
                    "Error al almacenar el Precio");
            //e.printStackTrace();
        }

    }

    public void nuevoPrecio() {
        jTPrecio.setText("");
        jTCodigoAreaCuerpo.setText("");
        jTValor.setText("");
        jTPrecio.grabFocus();
    }

    public void alInicio() {
        jTCodigoAreaCuerpo.setEnabled(false);
        jTValor.setEnabled(false);
        jBNuevo.setEnabled(false);
        jBRegistar.setEnabled(false);
    }

    public void despuesInicio() {
        jTCodigoAreaCuerpo.setEnabled(true);
        jTValor.setEnabled(true);
        jBNuevo.setEnabled(true);
        jBRegistar.setEnabled(true);
    }

    public void consultarPrecio() {
        if (jTPrecio.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite Id Precio");
        } else {
            try {
                // Se consulta la existencia del usuario en la BD
                Precio precio
                        = getControladorPrecio()
                                .consultar(jTPrecio.getText());

                if (precio != null) {
                    jTCodigoAreaCuerpo.setText(precio.getiDAreaCuerpo() + "");
                    jTValor.setText(precio.getValor());

                    int resp = JOptionPane.showConfirmDialog(null,
                            "¿Desea Modificar Precio?", "Alerta!",
                            JOptionPane.YES_NO_OPTION);
                    if (resp == 0) {
                        // Se habilitan los campos para módificar 
                        despuesInicio();
                    } else {
                        // NO hace nada
                    }
                } else {
                    despuesInicio();
                }

            } catch (Exception e1) {
                // TODO Auto-generated catch block
                //e1.printStackTrace();
                JOptionPane.showMessageDialog(null, "Precio NO existe");
            }
        }

    }

    public void textoCampos() {
        TextPrompt textIdentificacion = new TextPrompt("Id Precio", jTPrecio);
        TextPrompt textNombres = new TextPrompt("Id área del cuerpo", jTCodigoAreaCuerpo);
        TextPrompt textApellidos = new TextPrompt("Valor", jTValor);
    }

    public void cargarImagenesBotones() {
        ImageIcon icon = new ImageIcon("recursos/consultar.png");
        jBConsultar.setIcon(icon);
        ImageIcon icon2 = new ImageIcon("recursos/nuevo.png");
        jBNuevo.setIcon(icon2);
        ImageIcon icon3 = new ImageIcon("recursos/registrar.png");
        jBRegistar.setIcon(icon3);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBConsultar;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JButton jBRegistar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTCodigoAreaCuerpo;
    private javax.swing.JTextField jTPrecio;
    private javax.swing.JTextField jTValor;
    // End of variables declaration//GEN-END:variables
}
