/**
 *
 * Clase: GestionarTratamientos
 *
 * @version: 0.1
 *
 * @Fecha de creación: 17/06/2020
 *
 * Fecha de Modificación:
 *
 * @author migue 1102838994
 *
 * Copyrigth: CECAR
 *
 */
package edu.cecar.vistas;

import edu.cecar.componentes.TextPrompt;
import edu.cecar.componentes.baseDatos.ConectarMySQL;
import edu.cecar.controladores.ControladorAreaCuerpo;
import edu.cecar.controladores.ControladorTratamiento;
import edu.cecar.modelo.AreaCuerpo;
import edu.cecar.modelo.Tratamiento;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * 
 */
public class GestionarTratamientos extends javax.swing.JInternalFrame {

    private static ControladorTratamiento controladorTratamiento;

    /**
     * Creates new form GestionarUsuarios
     */
    public GestionarTratamientos() {
        initComponents();
        // Se hace que campo de texto Identidicación este listo para ser editado        
        jTTratamiento.grabFocus();

        alInicio();
        textoCampos();
        cargarImagenesBotones();

        // Realizamos la conexión con la base de datos
        try {
            ConectarMySQL.getConectarMySQL("127.0.0.1", "sif", "root", "");
        } catch (Exception e1) {
            // TODO Auto-generated catch block
            //e1.printStackTrace();
            JOptionPane.showMessageDialog(null,
                    "Error al conectar con la Base de datos");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTTratamiento = new javax.swing.JTextField();
        jTNombreTratamiento = new javax.swing.JTextField();
        jTIDPrecio = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jBNuevo = new javax.swing.JButton();
        jBRegistar = new javax.swing.JButton();
        jBConsultar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setTitle("Gestionar Tratamientos");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Información del Tratamiento", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 0, 18))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jPanel1.setLayout(null);

        jTTratamiento.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        jTTratamiento.setBorder(null);
        jTTratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTTratamientoActionPerformed(evt);
            }
        });
        jPanel1.add(jTTratamiento);
        jTTratamiento.setBounds(60, 40, 150, 30);

        jTNombreTratamiento.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        jTNombreTratamiento.setBorder(null);
        jPanel1.add(jTNombreTratamiento);
        jTNombreTratamiento.setBounds(30, 90, 210, 30);

        jTIDPrecio.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        jTIDPrecio.setBorder(null);
        jPanel1.add(jTIDPrecio);
        jTIDPrecio.setBounds(30, 140, 210, 30);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(50, 70, 170, 10);
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(30, 120, 210, 10);
        jPanel1.add(jSeparator4);
        jSeparator4.setBounds(30, 170, 210, 10);

        jPanel4.add(jPanel1);
        jPanel1.setBounds(30, 10, 290, 240);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Operaciones", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 0, 18))); // NOI18N
        jPanel2.setLayout(null);

        jBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoActionPerformed(evt);
            }
        });
        jPanel2.add(jBNuevo);
        jBNuevo.setBounds(10, 100, 150, 50);

        jBRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegistarActionPerformed(evt);
            }
        });
        jPanel2.add(jBRegistar);
        jBRegistar.setBounds(20, 160, 140, 50);

        jBConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultarActionPerformed(evt);
            }
        });
        jPanel2.add(jBConsultar);
        jBConsultar.setBounds(20, 40, 140, 50);

        jPanel4.add(jPanel2);
        jPanel2.setBounds(350, 20, 190, 230);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegistarActionPerformed

        // Se procede a realizar operaciones con los datos 
        if (jTTratamiento.getText().equals("")
                || jTNombreTratamiento.getText().equals("")
                || jTIDPrecio.getText().equals("")) {

            JOptionPane.showMessageDialog(null,
                    "Verificar los datos ingresados");
        } else {

            Tratamiento tratamiento
                    = new Tratamiento(Integer.parseInt(
                            jTTratamiento.getText()),
                            jTNombreTratamiento.getText(),
                            Integer.parseInt(jTIDPrecio.getText()));
            guardar(tratamiento);
        }

    }//GEN-LAST:event_jBRegistarActionPerformed

    private void jBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoActionPerformed

        nuevoTratamiento();
    }//GEN-LAST:event_jBNuevoActionPerformed

    private void jBConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultarActionPerformed

        consultarTratamiento();
    }//GEN-LAST:event_jBConsultarActionPerformed

    private void jTTratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTTratamientoActionPerformed

        consultarTratamiento();
    }//GEN-LAST:event_jTTratamientoActionPerformed

    public static ControladorTratamiento getControladorTratamiento() {

        if (controladorTratamiento == null) {
            controladorTratamiento = new ControladorTratamiento();
        }

        return controladorTratamiento;

    }

    public void guardar(Tratamiento tratamiento) {

        try {

            getControladorTratamiento().guardar(tratamiento);
            JOptionPane.showMessageDialog(null,
                    "Tratamiento Almacenado correctamente");
            nuevoTratamiento();
            alInicio();

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null,
                    "Error al almacenar el Tratamiento");
            //e.printStackTrace();
        }

    }

    public void nuevoTratamiento() {
        jTTratamiento.setText("");
        jTNombreTratamiento.setText("");
        jTIDPrecio.setText("");
        jTTratamiento.grabFocus();
    }

    public void alInicio() {
        jTNombreTratamiento.setEnabled(false);
        jTIDPrecio.setEnabled(false);
        jBNuevo.setEnabled(false);
        jBRegistar.setEnabled(false);
    }

    public void despuesInicio() {
        jTNombreTratamiento.setEnabled(true);
        jTIDPrecio.setEnabled(true);
        jBNuevo.setEnabled(true);
        jBRegistar.setEnabled(true);
    }

    public void consultarTratamiento() {
        if (jTTratamiento.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite Id Tratamiento");
        } else {
            try {
                // Se consulta la existencia del usuario en la BD
                Tratamiento tratamiento
                        = getControladorTratamiento()
                                .consultar(jTTratamiento.getText());

                if (tratamiento != null) {
                    jTNombreTratamiento.setText(tratamiento.getNombre());
                    jTIDPrecio.setText(tratamiento.getPrecio() + "");

                    int resp = JOptionPane.showConfirmDialog(null,
                            "¿Desea Modificar Tratamiento?", "Alerta!",
                            JOptionPane.YES_NO_OPTION);
                    if (resp == 0) {
                        // Se habilitan los campos para módificar 
                        despuesInicio();
                    } else {
                        // NO hace nada
                    }
                } else {
                    despuesInicio();
                }

            } catch (Exception e1) {
                // TODO Auto-generated catch block
                //e1.printStackTrace();
                JOptionPane.showMessageDialog(null, "Tratamiento NO existe");
            }
        }

    }

    public void textoCampos() {
        TextPrompt textIdentificacion = new TextPrompt("Código Tratamiento", jTTratamiento);
        TextPrompt textNombres = new TextPrompt("Nombre", jTNombreTratamiento);
        TextPrompt textApellidos = new TextPrompt("ID Precio", jTIDPrecio);
    }

    public void cargarImagenesBotones() {
        ImageIcon icon = new ImageIcon("recursos/consultar.png");
        jBConsultar.setIcon(icon);
        ImageIcon icon2 = new ImageIcon("recursos/nuevo.png");
        jBNuevo.setIcon(icon2);
        ImageIcon icon3 = new ImageIcon("recursos/registrar.png");
        jBRegistar.setIcon(icon3);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBConsultar;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JButton jBRegistar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTIDPrecio;
    private javax.swing.JTextField jTNombreTratamiento;
    private javax.swing.JTextField jTTratamiento;
    // End of variables declaration//GEN-END:variables
}
