/**
 *
 * Clase: GestionarSesiones
 *
 * @version: 0.1
 *
 * @Fecha de creación: 16/06/2020
 *
 * Fecha de Modificación:
 *
 * @author migue 1102838994
 *
 * Copyrigth: CECAR
 *
 */
package edu.cecar.vistas;

import edu.cecar.componentes.TextPrompt;
import edu.cecar.componentes.baseDatos.ConectarMySQL;
import edu.cecar.controladores.ContraladorSesion;
import edu.cecar.controladores.ControladorDatosEmpresa;
import edu.cecar.controladores.ControladorDiagnostico;
import edu.cecar.controladores.ControladorPaciente;
import edu.cecar.modelo.DatosEmpresa;
import edu.cecar.modelo.Diagnostico;
import edu.cecar.modelo.Paciente;
import edu.cecar.modelo.Sesion;
import static edu.cecar.vistas.MenuPrincipalSIF.jDEscritorio;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author migue
 */
public class GestionarSesiones extends javax.swing.JInternalFrame {

    private static ControladorDatosEmpresa controladorDatos;
    private static ControladorPaciente controladorPaciente;
    private static ControladorDiagnostico controladorDiagnostico;
    private static ContraladorSesion controladorSesion;

    /**
     * Creates new form GestionarUsuarios
     */
    public GestionarSesiones() {
        initComponents();
        // Se hace que campo de texto Identidicación este listo para ser editado        
        jTNitEmoresa.grabFocus();

        consultarDatos();
//        alInicio();
        textoCampos();
        cargarImagenesBotones();
        fechaSistema();

        // Realizamos la conexión con la base de datos
        try {
            ConectarMySQL.getConectarMySQL("127.0.0.1", "sif", "root", "");
        } catch (Exception e1) {
            // TODO Auto-generated catch block
            //e1.printStackTrace();
            JOptionPane.showMessageDialog(null,
                    "Error al conectar con la Base de datos");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPContenedor = new javax.swing.JPanel();
        jPSesion = new javax.swing.JPanel();
        jTIdSesion = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jTipeso = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jTFechaSesion = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jTPresion = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jTiTemperatura = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        jTNivelDolor = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAResultado = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jTNitEmoresa = new javax.swing.JTextField();
        jTNombreEmpresa = new javax.swing.JTextField();
        jTDireccion = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jPOperaciones = new javax.swing.JPanel();
        jBNuevo = new javax.swing.JButton();
        jBRegistar = new javax.swing.JButton();
        jBConsultar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTIdentidicacionPaciente = new javax.swing.JTextField();
        jTNombrePaciente = new javax.swing.JTextField();
        jTApellidoPaciente = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jPDetalleFactura1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTbDetalleServicios = new javax.swing.JTable();
        jPDiagnostico1 = new javax.swing.JPanel();
        jTIDDiagnostico = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTADiagnosticoGeneral = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTADiagEspesifico = new javax.swing.JTextArea();
        jSeparator15 = new javax.swing.JSeparator();
        jTNumeroSesiones = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setTitle("Gestionar Sesiones");

        jPContenedor.setBackground(new java.awt.Color(255, 255, 255));
        jPContenedor.setLayout(null);

        jPSesion.setBackground(new java.awt.Color(255, 255, 255));
        jPSesion.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Información de la Sesión", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 0, 12))); // NOI18N
        jPSesion.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jPSesion.setLayout(null);

        jTIdSesion.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        jTIdSesion.setBorder(null);
        jTIdSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTIdSesionActionPerformed(evt);
            }
        });
        jPSesion.add(jTIdSesion);
        jTIdSesion.setBounds(20, 30, 140, 20);
        jPSesion.add(jSeparator8);
        jSeparator8.setBounds(20, 50, 140, 10);

        jTipeso.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        jTipeso.setBorder(null);
        jTipeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTipesoActionPerformed(evt);
            }
        });
        jPSesion.add(jTipeso);
        jTipeso.setBounds(180, 30, 150, 20);
        jPSesion.add(jSeparator9);
        jSeparator9.setBounds(180, 50, 150, 10);

        jTFechaSesion.setEditable(false);
        jTFechaSesion.setBackground(new java.awt.Color(255, 255, 255));
        jTFechaSesion.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        jTFechaSesion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFechaSesion.setBorder(null);
        jTFechaSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFechaSesionActionPerformed(evt);
            }
        });
        jPSesion.add(jTFechaSesion);
        jTFechaSesion.setBounds(350, 30, 150, 20);
        jPSesion.add(jSeparator10);
        jSeparator10.setBounds(350, 50, 150, 10);

        jTPresion.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        jTPresion.setBorder(null);
        jTPresion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTPresionActionPerformed(evt);
            }
        });
        jPSesion.add(jTPresion);
        jTPresion.setBounds(20, 60, 140, 20);
        jPSesion.add(jSeparator11);
        jSeparator11.setBounds(20, 80, 140, 10);

        jTiTemperatura.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        jTiTemperatura.setBorder(null);
        jTiTemperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTiTemperaturaActionPerformed(evt);
            }
        });
        jPSesion.add(jTiTemperatura);
        jTiTemperatura.setBounds(180, 60, 150, 20);
        jPSesion.add(jSeparator12);
        jSeparator12.setBounds(180, 80, 150, 10);

        jTNivelDolor.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        jTNivelDolor.setBorder(null);
        jTNivelDolor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNivelDolorActionPerformed(evt);
            }
        });
        jPSesion.add(jTNivelDolor);
        jTNivelDolor.setBounds(350, 60, 150, 20);
        jPSesion.add(jSeparator13);
        jSeparator13.setBounds(350, 80, 150, 10);

        jTAResultado.setColumns(20);
        jTAResultado.setLineWrap(true);
        jTAResultado.setRows(5);
        jScrollPane1.setViewportView(jTAResultado);

        jPSesion.add(jScrollPane1);
        jScrollPane1.setBounds(510, 20, 390, 80);

        jPContenedor.add(jPSesion);
        jPSesion.setBounds(10, 110, 920, 110);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Factura de Servicio", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 0, 12))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jPanel1.setLayout(null);

        jTNitEmoresa.setEditable(false);
        jTNitEmoresa.setBackground(new java.awt.Color(255, 255, 255));
        jTNitEmoresa.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        jTNitEmoresa.setBorder(null);
        jTNitEmoresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNitEmoresaActionPerformed(evt);
            }
        });
        jPanel1.add(jTNitEmoresa);
        jTNitEmoresa.setBounds(10, 20, 150, 20);

        jTNombreEmpresa.setEditable(false);
        jTNombreEmpresa.setBackground(new java.awt.Color(255, 255, 255));
        jTNombreEmpresa.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        jTNombreEmpresa.setBorder(null);
        jPanel1.add(jTNombreEmpresa);
        jTNombreEmpresa.setBounds(10, 50, 190, 20);

        jTDireccion.setEditable(false);
        jTDireccion.setBackground(new java.awt.Color(255, 255, 255));
        jTDireccion.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        jTDireccion.setBorder(null);
        jPanel1.add(jTDireccion);
        jTDireccion.setBounds(210, 50, 180, 20);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(10, 40, 150, 10);
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(10, 70, 190, 10);
        jPanel1.add(jSeparator4);
        jSeparator4.setBounds(210, 70, 180, 10);

        jPContenedor.add(jPanel1);
        jPanel1.setBounds(530, 10, 400, 90);

        jPOperaciones.setBackground(new java.awt.Color(255, 255, 255));
        jPOperaciones.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Operaciones", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 0, 12))); // NOI18N
        jPOperaciones.setLayout(null);

        jBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoActionPerformed(evt);
            }
        });
        jPOperaciones.add(jBNuevo);
        jBNuevo.setBounds(10, 100, 150, 50);

        jBRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegistarActionPerformed(evt);
            }
        });
        jPOperaciones.add(jBRegistar);
        jBRegistar.setBounds(20, 160, 140, 50);

        jBConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultarActionPerformed(evt);
            }
        });
        jPOperaciones.add(jBConsultar);
        jBConsultar.setBounds(20, 40, 140, 50);

        jPContenedor.add(jPOperaciones);
        jPOperaciones.setBounds(650, 360, 190, 220);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Información del Paciente", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 0, 12))); // NOI18N
        jPanel3.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jPanel3.setLayout(null);

        jTIdentidicacionPaciente.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        jTIdentidicacionPaciente.setBorder(null);
        jTIdentidicacionPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTIdentidicacionPacienteActionPerformed(evt);
            }
        });
        jPanel3.add(jTIdentidicacionPaciente);
        jTIdentidicacionPaciente.setBounds(10, 20, 150, 20);

        jTNombrePaciente.setEditable(false);
        jTNombrePaciente.setBackground(new java.awt.Color(255, 255, 255));
        jTNombrePaciente.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        jTNombrePaciente.setBorder(null);
        jPanel3.add(jTNombrePaciente);
        jTNombrePaciente.setBounds(10, 50, 210, 20);

        jTApellidoPaciente.setEditable(false);
        jTApellidoPaciente.setBackground(new java.awt.Color(255, 255, 255));
        jTApellidoPaciente.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        jTApellidoPaciente.setBorder(null);
        jPanel3.add(jTApellidoPaciente);
        jTApellidoPaciente.setBounds(230, 50, 210, 20);
        jPanel3.add(jSeparator5);
        jSeparator5.setBounds(10, 40, 150, 10);
        jPanel3.add(jSeparator6);
        jSeparator6.setBounds(10, 70, 210, 10);
        jPanel3.add(jSeparator7);
        jSeparator7.setBounds(230, 70, 210, 10);

        jButton2.setText("+");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(440, 10, 50, 30);

        jPContenedor.add(jPanel3);
        jPanel3.setBounds(20, 10, 500, 90);

        jPDetalleFactura1.setBackground(new java.awt.Color(255, 255, 255));
        jPDetalleFactura1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Detalle Factura", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 0, 12))); // NOI18N
        jPDetalleFactura1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jPDetalleFactura1.setLayout(null);

        jButton4.setText("+");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPDetalleFactura1.add(jButton4);
        jButton4.setBounds(470, 20, 50, 30);

        jTbDetalleServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Detalle", "Nombre Tratamiento", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTbDetalleServicios);

        jPDetalleFactura1.add(jScrollPane3);
        jScrollPane3.setBounds(10, 30, 450, 140);

        jPContenedor.add(jPDetalleFactura1);
        jPDetalleFactura1.setBounds(20, 390, 540, 190);

        jPDiagnostico1.setBackground(new java.awt.Color(255, 255, 255));
        jPDiagnostico1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Diagnótico", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 0, 12))); // NOI18N
        jPDiagnostico1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jPDiagnostico1.setLayout(null);

        jTIDDiagnostico.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        jTIDDiagnostico.setBorder(null);
        jTIDDiagnostico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTIDDiagnosticoActionPerformed(evt);
            }
        });
        jPDiagnostico1.add(jTIDDiagnostico);
        jTIDDiagnostico.setBounds(10, 10, 140, 20);
        jPDiagnostico1.add(jSeparator14);
        jSeparator14.setBounds(10, 30, 140, 10);

        jTADiagnosticoGeneral.setColumns(20);
        jTADiagnosticoGeneral.setLineWrap(true);
        jTADiagnosticoGeneral.setRows(5);
        jScrollPane2.setViewportView(jTADiagnosticoGeneral);

        jPDiagnostico1.add(jScrollPane2);
        jScrollPane2.setBounds(10, 40, 340, 80);

        jTADiagEspesifico.setColumns(20);
        jTADiagEspesifico.setLineWrap(true);
        jTADiagEspesifico.setRows(5);
        jScrollPane4.setViewportView(jTADiagEspesifico);

        jPDiagnostico1.add(jScrollPane4);
        jScrollPane4.setBounds(370, 40, 340, 80);
        jPDiagnostico1.add(jSeparator15);
        jSeparator15.setBounds(750, 80, 140, 10);

        jTNumeroSesiones.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        jTNumeroSesiones.setBorder(null);
        jPDiagnostico1.add(jTNumeroSesiones);
        jTNumeroSesiones.setBounds(750, 60, 140, 20);

        jPContenedor.add(jPDiagnostico1);
        jPDiagnostico1.setBounds(10, 230, 920, 130);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 940, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegistarActionPerformed

//         Se procede a realizar operaciones con los datos 
        if (jTIDDiagnostico.getText().equals("") // Diagnostico
                || jTADiagnosticoGeneral.getText().equals("")
                || jTIdentidicacionPaciente.getText().equals("")
                || jTADiagEspesifico.getText().equals("")
                || jTNumeroSesiones.getText().equals("")
                || jTIdSesion.getText().equals("") // Sesiones
                || jTipeso.getText().equals("")
                || jTPresion.getText().equals("")
                || jTiTemperatura.getText().equals("")
                || jTNivelDolor.getText().equals("")
                || jTAResultado.getText().equals("")) {

            JOptionPane.showMessageDialog(null,
                    "Verificar los datos ingresados");
        } else {

            Diagnostico diagnostico
                    = new Diagnostico(Integer.parseInt(
                            jTIDDiagnostico.getText()),
                            Integer.parseInt(jTIdentidicacionPaciente.getText()),
                            jTADiagnosticoGeneral.getText(),
                            jTADiagEspesifico.getText(),
                            jTNumeroSesiones.getText());
            guardar(diagnostico);
            
            Sesion sesion
                    = new Sesion(Integer.parseInt(
                            jTIdSesion.getText()),
                            jTFechaSesion.getText(),
                            Integer.parseInt(jTIDDiagnostico.getText()),
                            jTipeso.getText(),
                            jTPresion.getText(),
                            jTiTemperatura.getText(),
                            jTNivelDolor.getText(),
                            jTAResultado.getText());
            guardarSesion(sesion);

        }

    }//GEN-LAST:event_jBRegistarActionPerformed

    private void jBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoActionPerformed


    }//GEN-LAST:event_jBNuevoActionPerformed

    private void jBConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultarActionPerformed


    }//GEN-LAST:event_jBConsultarActionPerformed

    private void jTNitEmoresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNitEmoresaActionPerformed


    }//GEN-LAST:event_jTNitEmoresaActionPerformed

    private void jTIdentidicacionPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTIdentidicacionPacienteActionPerformed
        consultarPaciente();
    }//GEN-LAST:event_jTIdentidicacionPacienteActionPerformed

    private void jTIdSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTIdSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTIdSesionActionPerformed

    private void jTipesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTipesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTipesoActionPerformed

    private void jTFechaSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFechaSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFechaSesionActionPerformed

    private void jTPresionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTPresionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTPresionActionPerformed

    private void jTiTemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTiTemperaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTiTemperaturaActionPerformed

    private void jTNivelDolorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNivelDolorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNivelDolorActionPerformed

    private void jTIDDiagnosticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTIDDiagnosticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTIDDiagnosticoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Tratamientos tratamientos = new Tratamientos();
        jDEscritorio.add(tratamientos);
        tratamientos.show();
    }//GEN-LAST:event_jButton4ActionPerformed

    public static ControladorDatosEmpresa getControladorDatos() {

        if (controladorDatos == null) {
            controladorDatos = new ControladorDatosEmpresa();
        }

        return controladorDatos;

    }

    public static ControladorPaciente getControladorPaciente() {

        if (controladorPaciente == null) {
            controladorPaciente = new ControladorPaciente();
        }

        return controladorPaciente;

    }

    public static ControladorDiagnostico getControladorDiagnostico() {

        if (controladorDiagnostico == null) {
            controladorDiagnostico = new ControladorDiagnostico();
        }

        return controladorDiagnostico;

    }

    public static ContraladorSesion getControladorSesion() {

        if (controladorSesion == null) {
            controladorSesion = new ContraladorSesion();
        }

        return controladorSesion;

    }

    public void guardar(Diagnostico diagnostico) {

        try {

            getControladorDiagnostico().guardar(diagnostico);
            JOptionPane.showMessageDialog(null,
                    "Diagnostico Almacenado correctamente");

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null,
                    "Error al almacenar el Diagnóstico");
            //e.printStackTrace();
        }

    }
    
    public void guardarSesion(Sesion sesion) {

        try {

            getControladorSesion().guardar(sesion);
            JOptionPane.showMessageDialog(null,
                    "Sesión Almacenada correctamente");

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null,
                    "Error al almacenar Sesión");
            //e.printStackTrace();
        }

    }

    public void nuevoAreaCuerpo() {
        jTNitEmoresa.setText("");
        jTNombreEmpresa.setText("");
        jTDireccion.setText("");
        jTNitEmoresa.grabFocus();
    }

    public void alInicio() {
        jBNuevo.setEnabled(false);
        jBRegistar.setEnabled(false);
    }

    public void despuesInicio() {
        jBNuevo.setEnabled(true);
        jBRegistar.setEnabled(true);
    }

    public void consultarDatos() {

        try {
            // Se consulta la existencia los datos en la BD
            DatosEmpresa datosEmpresa
                    = getControladorDatos()
                            .consultar("1");

            if (datosEmpresa != null) {
                jTNitEmoresa.setText("Nit: " + datosEmpresa.getNit());
                jTNombreEmpresa.setText("Nombre Empresa: " + datosEmpresa.getNombre());
                jTDireccion.setText("Dirección: " + datosEmpresa.getDireccion());

            }

        } catch (Exception e1) {
            // TODO Auto-generated catch block
            //e1.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al consultar datos");
        }

    }

    public void consultarPaciente() {

        if (jTIdentidicacionPaciente.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite identificación");
        } else {
            try {
                // Se consulta la existencia del usuario en la BD
                Paciente paciente
                        = getControladorPaciente()
                                .consultar(jTIdentidicacionPaciente.getText());

                if (paciente != null) {
                    jTNombrePaciente.setText("Nombres: " + paciente.getNombres());
                    jTApellidoPaciente.setText("Apellidos: " + paciente.getApellidos());

                }

            } catch (Exception e1) {
                // TODO Auto-generated catch block
                //e1.printStackTrace();
                JOptionPane.showMessageDialog(null, "Paciente NO existe");
            }
        }

    }

    public void textoCampos() {

        // Paciente
        TextPrompt textIdPaciente = new TextPrompt("Identificación", jTIdentidicacionPaciente);
        TextPrompt textNombres = new TextPrompt("Nombres", jTNombrePaciente);
        TextPrompt textApellidos = new TextPrompt("Apellidos", jTApellidoPaciente);

        // Sesión
        TextPrompt textIdSesion = new TextPrompt("Id Sesión", jTIdSesion);
        TextPrompt textIdPeso = new TextPrompt("Peso", jTipeso);
        TextPrompt textIdPresion = new TextPrompt("Presión Arterial", jTPresion);
        TextPrompt textIdTemperatura = new TextPrompt("Temperatura", jTiTemperatura);
        TextPrompt textIdNivelDolor = new TextPrompt("Nivel de Dolor", jTNivelDolor);
        TextPrompt textIdResultado = new TextPrompt("Resultado de la Sesión", jTAResultado);

        // Diagnóstico
        TextPrompt textIdDiagnistico = new TextPrompt("ID Diagnóstico", jTIDDiagnostico);
        TextPrompt textIdDiagnisticoGeneral = new TextPrompt("Diagnóstico General", jTADiagnosticoGeneral);
        TextPrompt textIdDiagnisticoEspesifico = new TextPrompt("Diagnóstico Espefico", jTADiagEspesifico);
        TextPrompt textNumerosesiones = new TextPrompt("Número Sesiones", jTNumeroSesiones);

    }

    public void cargarImagenesBotones() {
        ImageIcon icon = new ImageIcon("recursos/consultar.png");
        jBConsultar.setIcon(icon);
        ImageIcon icon2 = new ImageIcon("recursos/nuevo.png");
        jBNuevo.setIcon(icon2);
        ImageIcon icon3 = new ImageIcon("recursos/registrar.png");
        jBRegistar.setIcon(icon3);
    }

    public void fechaSistema() {
        Calendar c = Calendar.getInstance();
        String dia = Integer.toString(c.get(Calendar.DATE));
        String mes = Integer.toString(c.get(Calendar.MONTH) + 1);
        String annio = Integer.toString(c.get(Calendar.YEAR));
        jTFechaSesion.setText(annio + "-" + mes + "-" + dia);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBConsultar;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JButton jBRegistar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPContenedor;
    private javax.swing.JPanel jPDetalleFactura1;
    private javax.swing.JPanel jPDiagnostico1;
    private javax.swing.JPanel jPOperaciones;
    private javax.swing.JPanel jPSesion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextArea jTADiagEspesifico;
    private javax.swing.JTextArea jTADiagnosticoGeneral;
    private javax.swing.JTextArea jTAResultado;
    private javax.swing.JTextField jTApellidoPaciente;
    private javax.swing.JTextField jTDireccion;
    private javax.swing.JTextField jTFechaSesion;
    private javax.swing.JTextField jTIDDiagnostico;
    private javax.swing.JTextField jTIdSesion;
    private javax.swing.JTextField jTIdentidicacionPaciente;
    private javax.swing.JTextField jTNitEmoresa;
    private javax.swing.JTextField jTNivelDolor;
    private javax.swing.JTextField jTNombreEmpresa;
    private javax.swing.JTextField jTNombrePaciente;
    private javax.swing.JTextField jTNumeroSesiones;
    private javax.swing.JTextField jTPresion;
    private javax.swing.JTable jTbDetalleServicios;
    private javax.swing.JTextField jTiTemperatura;
    private javax.swing.JTextField jTipeso;
    // End of variables declaration//GEN-END:variables
}
