/**
 *
 * Clase: GestionarPacientes
 *
 * @version: 0.1
 *
 * @Fecha de creación: 14/06/2020
 *
 * Fecha de Modificación:
 *
 * @author migue 1102838994
 *
 * Copyrigth: CECAR
 *
 */
package edu.cecar.vistas;

import edu.cecar.componentes.TextPrompt;
import edu.cecar.componentes.baseDatos.ConectarMySQL;
import edu.cecar.controladores.ControladorPaciente;
import edu.cecar.modelo.Paciente;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author migue
 */
public class GestionarPacientes extends javax.swing.JInternalFrame {

    private static ControladorPaciente controladorPaciente;

    private static DefaultListModel modeloLista;

    /**
     * Creates new form GestionarUsuarios
     */
    public GestionarPacientes() {
        initComponents();
        // Se hace que campo de texto Identidicación este listo para ser editado        
        jTIdentificacion.grabFocus();

        alInicio();
        textoCampos();
        cargarImagenesBotones();

        // Realizamos la conexión con la base de datos
        try {
            ConectarMySQL.getConectarMySQL("127.0.0.1", "sif", "root", "");
        } catch (Exception e1) {
            // TODO Auto-generated catch block
            //e1.printStackTrace();
            JOptionPane.showMessageDialog(null,
                    "Error al conectar con la Base de datos");
        }

        jListTelefono = new JList<String>(getModeloLista());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListTelefono = new javax.swing.JList<>();
        jTIdentificacion = new javax.swing.JTextField();
        jCTipoIdentificacion = new javax.swing.JComboBox<>();
        jTNombres = new javax.swing.JTextField();
        jTApellidos = new javax.swing.JTextField();
        jTEmail = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jTtelefono = new javax.swing.JTextField();
        jBAgragarTelefono = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jBNuevo = new javax.swing.JButton();
        jBRegistar = new javax.swing.JButton();
        jBConsultar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setTitle("Gestionar Paciente");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Información del Paciente", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 0, 18))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jPanel1.setLayout(null);

        jListTelefono.setModel(getModeloLista());
        jScrollPane1.setViewportView(jListTelefono);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(300, 150, 160, 70);

        jTIdentificacion.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        jTIdentificacion.setBorder(null);
        jTIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTIdentificacionActionPerformed(evt);
            }
        });
        jPanel1.add(jTIdentificacion);
        jTIdentificacion.setBounds(60, 40, 150, 30);

        jCTipoIdentificacion.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        jCTipoIdentificacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de Documento", "CC", "Paporte" }));
        jPanel1.add(jCTipoIdentificacion);
        jCTipoIdentificacion.setBounds(310, 40, 170, 30);

        jTNombres.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        jTNombres.setBorder(null);
        jPanel1.add(jTNombres);
        jTNombres.setBounds(30, 90, 210, 30);

        jTApellidos.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        jTApellidos.setBorder(null);
        jPanel1.add(jTApellidos);
        jTApellidos.setBounds(30, 140, 210, 30);

        jTEmail.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        jTEmail.setBorder(null);
        jPanel1.add(jTEmail);
        jTEmail.setBounds(30, 190, 210, 30);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(50, 70, 170, 10);
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(30, 120, 210, 10);
        jPanel1.add(jSeparator4);
        jSeparator4.setBounds(30, 170, 210, 10);
        jPanel1.add(jSeparator6);
        jSeparator6.setBounds(30, 220, 210, 10);
        jPanel1.add(jSeparator7);
        jSeparator7.setBounds(270, 120, 150, 10);

        jTtelefono.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        jTtelefono.setBorder(null);
        jPanel1.add(jTtelefono);
        jTtelefono.setBounds(270, 90, 150, 30);

        jBAgragarTelefono.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jBAgragarTelefono.setText("+");
        jBAgragarTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgragarTelefonoActionPerformed(evt);
            }
        });
        jPanel1.add(jBAgragarTelefono);
        jBAgragarTelefono.setBounds(430, 80, 50, 50);

        jPanel4.add(jPanel1);
        jPanel1.setBounds(0, 0, 540, 270);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Operaciones", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 0, 18))); // NOI18N
        jPanel2.setLayout(null);

        jBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoActionPerformed(evt);
            }
        });
        jPanel2.add(jBNuevo);
        jBNuevo.setBounds(10, 100, 150, 50);

        jBRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegistarActionPerformed(evt);
            }
        });
        jPanel2.add(jBRegistar);
        jBRegistar.setBounds(20, 160, 140, 50);

        jBConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultarActionPerformed(evt);
            }
        });
        jPanel2.add(jBConsultar);
        jBConsultar.setBounds(20, 40, 140, 50);

        jPanel4.add(jPanel2);
        jPanel2.setBounds(570, 10, 190, 260);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 795, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegistarActionPerformed

        // Se procede a realizar operaciones con los datos 
        if (jTIdentificacion.getText().equals("")
                || jCTipoIdentificacion.getSelectedItem()
                        .toString().equals("Tipo de Documento")
                || jTNombres.getText().equals("")
                || jTApellidos.getText().equals("")
                || jTEmail.getText().equals("")) {

            JOptionPane.showMessageDialog(null,
                    "Verificar los datos ingresados");
        } else {

            Paciente paciente
                    = new Paciente(Integer.parseInt(
                            jTIdentificacion.getText()),
                            jCTipoIdentificacion.getSelectedItem().toString(),
                            jTNombres.getText(),
                            jTApellidos.getText(),
                            jTEmail.getText(),
                            getModeloLista().toArray());
            guardar(paciente);
        }

    }//GEN-LAST:event_jBRegistarActionPerformed

    private void jBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoActionPerformed

        nuevoPaciente();
    }//GEN-LAST:event_jBNuevoActionPerformed

    private void jBConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultarActionPerformed

        consultarPaciente();
    }//GEN-LAST:event_jBConsultarActionPerformed

    private void jTIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTIdentificacionActionPerformed

        consultarPaciente();
    }//GEN-LAST:event_jTIdentificacionActionPerformed

    private void jBAgragarTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgragarTelefonoActionPerformed
        if (jTtelefono.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite Número de teléfono");
        } else {
            getModeloLista().addElement(jTtelefono.getText());
            System.out.println(getModeloLista());
            jTtelefono.setText("");
            jTtelefono.grabFocus();
        }

    }//GEN-LAST:event_jBAgragarTelefonoActionPerformed

    public static ControladorPaciente getControladorPaciente() {

        if (controladorPaciente == null) {
            controladorPaciente = new ControladorPaciente();
        }

        return controladorPaciente;

    }

    public void guardar(Paciente paciente) {

        try {

            getControladorPaciente().guardar(paciente);
            JOptionPane.showMessageDialog(null,
                    "Paciente Almacenado correctamente");
            nuevoPaciente();
            alInicio();

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null,
                    "Error al almacenar el Paciente");
            //e.printStackTrace();
        }

    }

    public void nuevoPaciente() {
        jTIdentificacion.setText("");
        jCTipoIdentificacion.setSelectedItem("Tipo de Documento");
        jTNombres.setText("");
        jTApellidos.setText("");
        jTEmail.setText("");
        getModeloLista().removeAllElements();
        jTIdentificacion.grabFocus();
    }

    public void alInicio() {
        jCTipoIdentificacion.setEnabled(false);
        jTNombres.setEnabled(false);
        jTApellidos.setEnabled(false);
        jTEmail.setEnabled(false);
        jTtelefono.setEnabled(false);
        jBNuevo.setEnabled(false);
        jBRegistar.setEnabled(false);
        jBAgragarTelefono.setEnabled(false);
    }

    public void despuesInicio() {
        jCTipoIdentificacion.setEnabled(true);
        jTNombres.setEnabled(true);
        jTApellidos.setEnabled(true);
        jTEmail.setEnabled(true);
        jTtelefono.setEnabled(true);
        jBNuevo.setEnabled(true);
        jBRegistar.setEnabled(true);        
        jBAgragarTelefono.setEnabled(true);
    }

    public void consultarPaciente() {
        if (jTIdentificacion.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite identificación");
        } else {
            try {
                // Se consulta la existencia del usuario en la BD
                Paciente paciente
                        = getControladorPaciente()
                                .consultar(jTIdentificacion.getText());

                if (paciente != null) {
                    jCTipoIdentificacion.setSelectedItem(paciente.getTipoIdentificacion());
                    jTNombres.setText(paciente.getNombres());
                    jTApellidos.setText(paciente.getApellidos());
                    jTEmail.setText(paciente.getEmail());

                    int resp = JOptionPane.showConfirmDialog(null,
                            "¿Desea Modificar Paciente?", "Alerta!",
                            JOptionPane.YES_NO_OPTION);
                    if (resp == 0) {
                        // Se habilitan los campos para módificar 
                        despuesInicio();
                    } else {
                        // NO hace nada
                    }
                } else {
                    despuesInicio();
                }

            } catch (Exception e1) {
                // TODO Auto-generated catch block
                //e1.printStackTrace();
                JOptionPane.showMessageDialog(null, "Paciente NO existe");
            }
        }

    }

    public void textoCampos() {
        TextPrompt textIdentificacion = new TextPrompt("Identificación", jTIdentificacion);
        TextPrompt textNombres = new TextPrompt("Nombres", jTNombres);
        TextPrompt textApellidos = new TextPrompt("Apellidos", jTApellidos);
        TextPrompt textEmail = new TextPrompt("Email", jTEmail);
        TextPrompt textTelefono = new TextPrompt("Teléfono", jTtelefono);
    }

    public void cargarImagenesBotones() {
        ImageIcon icon = new ImageIcon("recursos/consultar.png");
        jBConsultar.setIcon(icon);
        ImageIcon icon2 = new ImageIcon("recursos/nuevo.png");
        jBNuevo.setIcon(icon2);
        ImageIcon icon3 = new ImageIcon("recursos/registrar.png");
        jBRegistar.setIcon(icon3);
    }

    public static DefaultListModel<String> getModeloLista() {

        if (modeloLista == null) {
            modeloLista = new DefaultListModel<String>();
        }

        return modeloLista;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBAgragarTelefono;
    private javax.swing.JButton jBConsultar;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JButton jBRegistar;
    private javax.swing.JComboBox<String> jCTipoIdentificacion;
    private javax.swing.JList<String> jListTelefono;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField jTApellidos;
    private javax.swing.JTextField jTEmail;
    private javax.swing.JTextField jTIdentificacion;
    private javax.swing.JTextField jTNombres;
    private javax.swing.JTextField jTtelefono;
    // End of variables declaration//GEN-END:variables
}
