/**
 *
 * Clase: IngresoUsuarios
 *
 * @version: 0.1
 *
 * @Fecha de creación: 13/06/2020
 *
 * Fecha de Modificación:
 *
 * @author migue 1102838994
 *
 * Copyrigth: CECAR
 *
 */
package edu.cecar.vistas;

import edu.cecar.componentes.TextPrompt;
import edu.cecar.componentes.baseDatos.ConectarMySQL;
import edu.cecar.controladores.ControladorUsuario;
import edu.cecar.modelo.Usuario;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * Con está clase se validad el ingreso de los usarios al sistema
 *
 */
public class IngresoUsuarios extends javax.swing.JFrame {

    private static ControladorUsuario controladorUsuario;

    MenuPrincipalSIF ingreso = new MenuPrincipalSIF();

    /**
     * Creates new form IngresoUsuarios
     */
    public IngresoUsuarios() {
        initComponents();
        
        // Texto de las jTextFiel
         TextPrompt usuario = new TextPrompt("Usuario", jTUsuario);
        TextPrompt clave = new TextPrompt("Contraseña", jPassContrasena);
        
        // Imagen 
        ImageIcon icon = new ImageIcon("recursos/login.png");
        jLImagen.setIcon(icon);
        ImageIcon icon1 = new ImageIcon("recursos/ingresar.png");
        jBIngresar.setIcon(icon1);
        
        
        try {
            ConectarMySQL.getConectarMySQL("127.0.0.1", "sif", "root", "");
        } catch (Exception e1) {
            // TODO Auto-generated catch block
            //e1.printStackTrace();
            JOptionPane.showMessageDialog(null,
                    "Error al conectar con la Base de datos");
        }

        // Se hace que campo de texto usuario este listo para ser editado
        jTUsuario.grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBIngresar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jTUsuario = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jPassContrasena = new javax.swing.JPasswordField();
        jLImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ingreso Usuarios");
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jBIngresar.setBorder(null);
        jBIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(jBIngresar);
        jBIngresar.setBounds(130, 340, 180, 60);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(110, 270, 220, 10);

        jTUsuario.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jTUsuario.setBorder(null);
        jTUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(jTUsuario);
        jTUsuario.setBounds(130, 240, 180, 30);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(110, 320, 220, 10);

        jPassContrasena.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jPassContrasena.setBorder(null);
        jPassContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPassContrasenaActionPerformed(evt);
            }
        });
        jPanel1.add(jPassContrasena);
        jPassContrasena.setBounds(130, 290, 180, 30);
        jPanel1.add(jLImagen);
        jLImagen.setBounds(90, 10, 260, 220);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 460, 460);

        setSize(new java.awt.Dimension(473, 503));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIngresarActionPerformed
        
        // Se procede a ingresar al sistema
        ingresarSistema();

    }//GEN-LAST:event_jBIngresarActionPerformed

    private void jPassContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPassContrasenaActionPerformed
        
        // Se procede a ingresar al sistema
        ingresarSistema();
        
    }//GEN-LAST:event_jPassContrasenaActionPerformed

    private void jTUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTUsuarioActionPerformed
        jPassContrasena.grabFocus();
    }//GEN-LAST:event_jTUsuarioActionPerformed

    public static ControladorUsuario getControladorUsuario() {

        if (controladorUsuario == null) {
            controladorUsuario = new ControladorUsuario();
        }

        return controladorUsuario;

    }

    public void ingresarSistema() {
        try {
            // Se consulta la existencia del usuario en la BD
            Usuario usuario
                    = getControladorUsuario()
                            .consultar(jTUsuario.getText());

            if (usuario != null) {

                // Se validan las credenciales
                if (jTUsuario.getText()
                        .equals(usuario.getIdentificacionUsuario() + "")
                        && jPassContrasena.getText()
                                .equals(usuario.getContrasena())) {

                    //Se valida el tipo de usuario
                    switch (usuario.getTipoUsuario()) {
                        case 0: // Si es administador 
                            JOptionPane.showMessageDialog(null,
                                    "Bienvenid@ "
                                    + usuario.getNombres());
                            ingreso.setVisible(true);
                            ingreso.jMIPacientes.setEnabled(false);
                            ingreso.jMTratamientos.setEnabled(false);
                            ingreso.jMSesiones.setEnabled(false);
                            ingreso.pack();
                            dispose();
                            break;
                        case 1: // Si es fisioterapeuta
                            JOptionPane.showMessageDialog(null,
                                    "Bienvenid@ "
                                    + usuario.getNombres());
                            ingreso.setVisible(true);
                            ingreso.jMIUsuarios.setEnabled(false);
                            ingreso.jMITPrecioTratamientos.setEnabled(false);
                            ingreso.jMIAreasCuerpo.setEnabled(false);
                            ingreso.jMIPacientes.setEnabled(false);
                            ingreso.pack();
                            dispose();
                            break;
                        case 2: // Si es secretaria 
                            JOptionPane.showMessageDialog(null,
                                    "Bienvenid@ "
                                    + usuario.getNombres());
                            ingreso.setVisible(true);
                            ingreso.jMIUsuarios.setEnabled(false);
                            ingreso.jMITPrecioTratamientos.setEnabled(false);
                            ingreso.jMIAreasCuerpo.setEnabled(false);
                            ingreso.jMTratamientos.setEnabled(false);
                            ingreso.jMSesiones.setEnabled(false);
                            ingreso.pack();
                            dispose();
                            break;
                        default:
                            break;
                    }

                } else {
                    // Se informa al usuario que los datos son incorrectos
                    JOptionPane.showMessageDialog(null, "Datos Incorrectos");
                }
            }
        } catch (Exception e1) {
            // TODO Auto-generated catch block
            //e1.printStackTrace();
            JOptionPane.showMessageDialog(null, "Usuario NO existe");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresoUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresoUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresoUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresoUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresoUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBIngresar;
    private javax.swing.JLabel jLImagen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPassContrasena;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTUsuario;
    // End of variables declaration//GEN-END:variables
}
