/**
 *
 * Clase: MenuPrincipalSIF
 *
 * @version: 0.1
 *
 * @Fecha de creación: 13/06/2020
 *
 * Fecha de Modificación:
 *
 * @author migue 1102838994
 *
 * Copyrigth: CECAR
 *
 */
package edu.cecar.vistas;

/**
 *
 * @author migue
 */
public class MenuPrincipalSIF extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipalSIF
     */
    public MenuPrincipalSIF() {
        initComponents();
        this.setLocation(200, 50);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        jDEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMIUsuarios = new javax.swing.JMenuItem();
        jMITPrecioTratamientos = new javax.swing.JMenuItem();
        jMIAreasCuerpo = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMIPacientes = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú Principal");

        jMenu1.setText("Archivos");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Gestionar ");
        jMenu2.setToolTipText("");

        jMIUsuarios.setText("Usuarios");
        jMIUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIUsuariosActionPerformed(evt);
            }
        });
        jMenu2.add(jMIUsuarios);

        jMITPrecioTratamientos.setText("Precios de Tratamientos");
        jMenu2.add(jMITPrecioTratamientos);

        jMIAreasCuerpo.setText("Areas del Cuerpo");
        jMIAreasCuerpo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAreasCuerpoActionPerformed(evt);
            }
        });
        jMenu2.add(jMIAreasCuerpo);
        jMenu2.add(jSeparator1);

        jMIPacientes.setText("Pacientes");
        jMIPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIPacientesActionPerformed(evt);
            }
        });
        jMenu2.add(jMIPacientes);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Informes");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 863, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMIUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIUsuariosActionPerformed

        GestionarUsuarios gestionarUsuarios = new GestionarUsuarios();
        jDEscritorio.add(gestionarUsuarios);
        gestionarUsuarios.show();

    }//GEN-LAST:event_jMIUsuariosActionPerformed

    private void jMIPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIPacientesActionPerformed
        
        GestionarPacientes gestionarPacientes = new GestionarPacientes();
        jDEscritorio.add(gestionarPacientes);
        gestionarPacientes.show();
    }//GEN-LAST:event_jMIPacientesActionPerformed

    private void jMIAreasCuerpoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAreasCuerpoActionPerformed
       
        GestionarAreaCuerpo gestionarAreas = new GestionarAreaCuerpo();
        jDEscritorio.add(gestionarAreas);
        gestionarAreas.show();
    }//GEN-LAST:event_jMIAreasCuerpoActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MenuPrincipalSIF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MenuPrincipalSIF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MenuPrincipalSIF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MenuPrincipalSIF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MenuPrincipalSIF().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDEscritorio;
    private javax.swing.JMenuItem jMIAreasCuerpo;
    private javax.swing.JMenuItem jMIPacientes;
    private javax.swing.JMenuItem jMITPrecioTratamientos;
    private javax.swing.JMenuItem jMIUsuarios;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
