/**
 *
 * Clase: Tratamientos
 *
 * @version: 0.1
 *
 * @Fecha de creación: 16/06/2020
 *
 * Fecha de Modificación:
 *
 * @author migue 1102838994
 *
 * Copyrigth: CECAR
 *
 */
package edu.cecar.vistas;

import edu.cecar.componentes.baseDatos.ConectarMySQL;
import edu.cecar.controladores.ControladorTratamiento;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author migue
 */
public class Tratamientos extends javax.swing.JInternalFrame {
    
    private static ControladorTratamiento controladorTratamiento;
    
    DefaultTableModel tabla;

    /**
     * Creates new form Tratamientos
     */
    public Tratamientos() {
        initComponents();
        cargarDatos();
        
        // Realizamos la conexión con la base de datos
        try {
            ConectarMySQL.getConectarMySQL("127.0.0.1", "sif", "root", "");
        } catch (Exception e1) {
            // TODO Auto-generated catch block
            //e1.printStackTrace();
            JOptionPane.showMessageDialog(null,
                    "Error al conectar con la Base de datos");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTaTratamientos = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("Tratamientos");
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jTaTratamientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTaTratamientos);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(40, 40, 350, 180);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-6, -2, 460, 290);

        setBounds(0, 0, 460, 313);
    }// </editor-fold>//GEN-END:initComponents
    
    public static ControladorTratamiento getControladorTratamiento() {

        if (controladorTratamiento == null) {
            controladorTratamiento = new ControladorTratamiento();
        }

        return controladorTratamiento;

    }
    
    public void cargarDatos(){
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTaTratamientos;
    // End of variables declaration//GEN-END:variables
}
